import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " flex flex-col items-center minh-screen w-full"
        }
      >
        <Providers>
          <header>
            <Sidebar />
          </header>
          <main className="flex minh-screen flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
