import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex flex-col items-center min-h-screen w-full bg-white relative"
        }
      >
        <Providers>
          <header className="relative">
            <Sidebar />
          </header>
          <main className="flex min-h-screen flex-col md:container items-center w-full py-10 px-16">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
